/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import GlorySchema.GameBoard.GameBoardScreen;
import GlorySchema.GameBoard.GameBoard;
import GlorySchema.ThreadsToUpdateUI.updateGameResult;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author MELANI
 */
public class GameResult extends javax.swing.JFrame {

    public GameResult() {
//        moved = false;

        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);

        ShowGrid();
        tblGames.setOpaque(true);
        levelScore.setText("Level " + (GameBoard.levelNo - 1) + " Score");

        updateGameResult t = new updateGameResult();
        t.start();
        t.sleepThread();
        t.shutdown();
    }

//    public void getLevelRanking() {
//        Results results = new Results();
//         try {
//            ResultSet rs = null;
//            String data[][] = null;
//
//            rs = results.getRanking(GameBord.levelNo-1);
//            ResultSetMetaData rsmd = rs.getMetaData();
//
//            rs.last();
//            int count = rs.getRow();
//            rs.beforeFirst();
//            data = new String[count][5];
//            int x = 0;
//            while (rs.next()) {
//                Vector v = new Vector();
//                DefaultTableModel dtf = (javax.swing.table.DefaultTableModel) tblGames.getModel();
//                v.add(data[x][0] = rs.getString("Name"));
//                v.add(data[x][1] = rs.getString("Level"+(GameBord.levelNo-1)+"Score"));
//                v.add(data[x][2] = rs.getString("Total"));
////                v.add(data[x][3] = rs.getString(""));
////                v.add(data[x][4] = rs.getString(""));
//                dtf.addRow(v);
//                //confirm = rs.getInt("confirm");
//                x = x + 1;
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(SelectGame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//    }
    private void ShowGrid() {
        String data[][] = null;
        String colu[] = new String[]{"Player", "Level Score", "Total"};
        DefaultTableModel model = new DefaultTableModel(data, colu) {
            //@Override
            public boolean isCellEditable(int x, int y) {
                if (y == 1) {
                    return true;
                } else {
                    return false;
                }
            }
        };

        tblGames.setModel(model);
        tblGames.getTableHeader().setPreferredSize(new Dimension(tblGames.getTableHeader().getPreferredSize().width, 35));
        JTableHeader head = tblGames.getTableHeader();
        head.setFont(head.getFont().deriveFont(Font.BOLD));

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tblGames.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
        tblGames.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);

        // model.setRowCount(20);
        TableColumn col0 = tblGames.getColumnModel().getColumn(1);
        col0.setMinWidth(80);
        col0.setPreferredWidth(80);
        col0.setMaxWidth(80);

        TableColumn col1 = tblGames.getColumnModel().getColumn(1);
        col1.setMinWidth(80);
        col1.setPreferredWidth(80);
        col1.setMaxWidth(80);

        TableColumn col2 = tblGames.getColumnModel().getColumn(2);
        col2.setMinWidth(80);
        col2.setPreferredWidth(80);
        col2.setMaxWidth(80);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        levelScore = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGames = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        levelScore.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        levelScore.setForeground(new java.awt.Color(0, 0, 153));
        levelScore.setText("SCORE");
        jPanel1.add(levelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 250, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phoenix50.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 50, 50));

        tblGames.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tblGames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblGames);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 640, 290));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 120, 40));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 3, 270, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if ((GameBoard.levelNo - 1) < 5) {
            GameBoardScreen gameBoard = new GameBoardScreen();
            gameBoard.setVisible(true);
            this.dispose();
        } else {
            SummaryOfGame summary = new SummaryOfGame();
            summary.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GameResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GameResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GameResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GameResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GameResult().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel levelScore;
    public static javax.swing.JTable tblGames;
    // End of variables declaration//GEN-END:variables
}
