/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author CHAMOD
 */
public class HowToPlay extends javax.swing.JFrame {

    /**
     * Creates new form HowToPlay
     */
    public HowToPlay() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        btnLeader.setContentAreaFilled(false);
        btnLeader.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnLeader = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 102, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1.When player join to the game in very first time\n   player needs to create a user account. \n2.If he/she is not an existing player then he/she\n   has to sign up to the game.\n3.Player has to select a game mode \n   (Ex: two player game, three player game, four \n   player game) according to his/her choice.\n4.Then database will consider the players who \n   are logged in to the game and replace them \n   to the game according to the requested type of game. \n   If there aren’t any players logged in to the game \n   or requested type of the game is not matched with \n   the other players that player has to wait until \n   some another player log in to the game. Because this is a multiplayer game.\n5.If the player’s sessions has been completed he/she\n   can play the game.\n6.The game already consists face up three initial letters.\n   Those letters are the only letters visible to all players.\n7.Game board consists a letter bag, so player can\n   select either consonant or vowel one after one according to his/her desire.\n8.After drawn has made, each player is allowed to \n   change either one consonant or one vowel.\n9.Player has to find the longest English word \n   that uses all the letters, each letter must be used at most once. Has to use the keyboard to input the word.\n10.Game calculates score using the word \n   that has inputted by the player through set of scoring rules at each round of play.\n11.Calculates the total score using each round’s scores.\n12.Find the winner of the game using total score \n   of each player.\n");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 370, 250));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("How To Play");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 190, -1));

        btnLeader.setBackground(new java.awt.Color(56, 185, 33));
        btnLeader.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnLeader.setForeground(new java.awt.Color(255, 255, 255));
        btnLeader.setText("Ok");
        btnLeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaderActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 120, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/result.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 170, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/smallleaves.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/smallleaves.gif"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaderActionPerformed
        SelectGame select = new SelectGame();
        select.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLeaderActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
