/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import GlorySchema.LeaderBoard;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Melanie Rebecca
 */
public class LeaderBoardScreen extends javax.swing.JFrame {

    LeaderBoard result = new LeaderBoard();
    String leaderTOp[][];

    /**
     * Creates new form LeaderBoard
     */
    public LeaderBoardScreen() {
        initComponents();
        ShowGrid();
        getLevelRanking();
        btnBack.setContentAreaFilled( false );
        btnBack.setBorder( null );
    }

    public void getLevelRanking() {
        try {
            ResultSet rs = null;
            String data[][] = null;

            rs = result.getTopRanking();//todomel
            ResultSetMetaData rsmd = rs.getMetaData();

            rs.last();
            int count = rs.getRow();
            rs.beforeFirst();
            data = new String[count][5];
            int x = 0;
            while (rs.next()) {
                Vector v = new Vector();
                DefaultTableModel dtf = (javax.swing.table.DefaultTableModel) leaderBoardtbl.getModel();
                v.add(data[x][0] = rs.getString("Name"));
                v.add(data[x][1] = rs.getString("Score"));
                dtf.addRow(v);
                x = x + 1;
            }

        } catch (SQLException ex) {
            Logger.getLogger(SelectGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ShowGrid() {
        String data[][] = null;
        String colu[] = new String[]{"Player", "Score"};
        DefaultTableModel model = new DefaultTableModel(data, colu) {
            //@Override
            public boolean isCellEditable(int x, int y) {
                if (y == 1) {
                    return true;
                } else {
                    return false;
                }
            }
        };

        leaderBoardtbl.setModel(model);
        leaderBoardtbl.getTableHeader().setPreferredSize(new Dimension(leaderBoardtbl.getTableHeader().getPreferredSize().width, 35));
        JTableHeader head = leaderBoardtbl.getTableHeader();
        head.setFont(head.getFont().deriveFont(Font.BOLD));

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);

    }

    private void getLeaderScore() {
        try {
            ResultSet rs = null;
            ResultSet rs1 = null;

            rs1 = result.getLeaderTopScore();//todomel
            ResultSetMetaData rsmd1 = rs1.getMetaData();

            rs = result.getLeaderTopScore();//todomel
            ResultSetMetaData rsmd = rs.getMetaData();

            rs.last();
            rs1.last();

            int count = rs.getRow() + rs1.getRow();

            rs1.beforeFirst();
            rs.beforeFirst();

            leaderTOp = new String[count][2];

            int x = 0;
            while (rs.next()) {
                Vector v = new Vector();
                DefaultTableModel dtf = (javax.swing.table.DefaultTableModel) leaderBoardtbl.getModel();
                v.add(leaderTOp[x][0] = rs.getString("Name"));
                v.add(leaderTOp[x][1] = rs.getString("Score"));//todomel
                dtf.addRow(v);
                x = x + 1;
            }

            while (rs1.next()) {
                Vector v = new Vector();
                DefaultTableModel dtf = (javax.swing.table.DefaultTableModel) leaderBoardtbl.getModel();
                v.add(leaderTOp[x][0] = rs1.getString("Name"));
                v.add(leaderTOp[x][1] = rs1.getString("Score"));
                dtf.addRow(v);
                x = x + 1;
            }

        } catch (SQLException ex) {
            Logger.getLogger(SelectGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getUpdateScore() {
        String temp[][];
        for (int i = 0; i < leaderTOp.length; i++) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leaderBoardtbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/smallleaves.gif"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        leaderBoardtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(leaderBoardtbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 530, 180));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phoenix50.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/smallleaves.gif"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBack.setBackground(new java.awt.Color(56, 185, 33));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons8-back-arrow-25(1).png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 180, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hight Score");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        SelectGame select = new SelectGame();
        select.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable leaderBoardtbl;
    // End of variables declaration//GEN-END:variables
}
