/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Db.DataBase;
import GlorySchema.Validation;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author deela
 */
public class LoginScreen extends javax.swing.JFrame {

    public static String PlayerId;
    public static String PlayerName;

    Validation value = new Validation();

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {

        setUndecorated(true);
//        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
//        setSize(852, 480);
        initComponents();
        btnLogin.setContentAreaFilled( false );
        btnLogin.setBorder( null );
        btnregister.setContentAreaFilled( false );        
        btnregister.setBorder( null );
        btnQuit.setContentAreaFilled( false );
        btnQuit.setBorder( null );
        txtUsername.setOpaque(false);
        txtUsername.setBorder( null );
        txt_password.setOpaque(false);
        txt_password.setBorder( null );

        setLocationRelativeTo(null);
        
        //  btnLoging.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btnQuit = new javax.swing.JButton();
        btnregister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 310, 40));

        txt_password.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 300, 40));

        btnQuit.setBackground(new java.awt.Color(56, 185, 33));
        btnQuit.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons8-shutdown-25.png"))); // NOI18N
        btnQuit.setText("QUIT");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel2.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 120, 40));

        btnregister.setBackground(new java.awt.Color(56, 185, 33));
        btnregister.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnregister.setForeground(new java.awt.Color(255, 255, 255));
        btnregister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnRegister.png"))); // NOI18N
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        jPanel2.add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 630, 200, 60));

        btnLogin.setBackground(new java.awt.Color(102, 102, 255));
        btnLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 130, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phoenix50.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 500, 570));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 190, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (!value.checkNull(txtUsername.getText(), "User name")) {
            return;
        } else if (!value.checkNull(txt_password.getText(), "Password")) {
            return;
        }

        try {
            DataBase db = new DataBase();
            String username = txtUsername.getText();
            ResultSet rs = null;

            String query = "SELECT * FROM player WHERE UserName  = '" + username + "'";
            rs = (ResultSet) db.fetch(query);
            if (rs.next()) {
                PlayerName = rs.getString("Name");
                PlayerId = rs.getString("UserId");
                if (txt_password.getText().equals(rs.getString("Password"))) {
                    // JOptionPane.showMessageDialog(null, "Success", "InfoBox: " + "Done", JOptionPane.INFORMATION_MESSAGE);
                    SelectGame breq = new SelectGame();
                    breq.setVisible(true);
                    this.dispose();
                    breq = null;

                } else {
                    JOptionPane.showMessageDialog(null, "Failed", "InfoBox: " + "Error", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        RegisterScreen register = new RegisterScreen();
        register.setVisible(true);
        this.dispose();

//  txtUsername.setText(null);
        //  txt_password.setText(null);
        //  this.hide();
        //  new RegisterScreen().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnQuitActionPerformed

//    private int oneX = 7;
//    private int oneY = 7;
//
//    boolean up = false;
//    boolean down = true;
//    boolean left = false;
//    boolean right = true;
//    
//     private void moveIt() {
//        while(true){
//            if(oneX >= 283){
//                right = false;
//                left = true;
//            }
//            if(oneX <= 7){
//                right = true;
//                left = false;
//            }
//            if(oneY >= 259){
//                up = true;
//                down = false;
//            }
//            if(oneY <= 7){
//                up = false;
//                down = true;
//            }
//            if(up){
//                oneY--;
//            }
//            if(down){
//                oneY++;
//            }
//            if(left){
//                oneX--;
//            }
//            if(right){
//                oneX++;
//            }
//            try{
//                Thread.sleep(10);
//            } catch (Exception exc){}
//            this.repaint();
//        }
//    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//            if ("Metal".equals(info.getName())) {
//                javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                MetalLookAndFeel.setCurrentTheme(new OceanTheme());
//                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

                break;
//            }

            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnregister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
