/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import GlorySchema.GameBoard.GameBoardScreen;
import GlorySchema.GameType;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author CHAMOD
 */
public class SelectGame extends javax.swing.JFrame {

    GameType game = new GameType();

    public SelectGame() {
        setUndecorated(true);
//        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
//        setSize(852, 480);
        initComponents();
        ShowGrid();
        getGameData(); // show current Games

        //rdb2Player.setOpaque(false);
        tblGames.setOpaque(true);
        setLocationRelativeTo(null);
    }

    private void getGameData() {
        try {
            ResultSet rs = null;
            String data[][] = null;

            rs = game.getGameTypes("");
            ResultSetMetaData rsmd = rs.getMetaData();

            rs.last();
            int count = rs.getRow();
            rs.beforeFirst();
            data = new String[count][5];
            int x = 0;
            while (rs.next()) {
                Vector v = new Vector();
                DefaultTableModel dtf = (javax.swing.table.DefaultTableModel) tblGames.getModel();
                v.add(data[x][0] = rs.getString("gameId"));
                v.add(data[x][1] = rs.getString("Description"));
                v.add(data[x][2] = rs.getString("currentPlayers"));
//                v.add(data[x][3] = rs.getString(""));
//                v.add(data[x][4] = rs.getString(""));
                dtf.addRow(v);
                //confirm = rs.getInt("confirm");
                x = x + 1;
            }

        } catch (SQLException ex) {
            Logger.getLogger(SelectGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ShowGrid() {
        String data[][] = null;
        String colu[] = new String[]{"Game Id", "Game Type", "Connected players"};
        DefaultTableModel model = new DefaultTableModel(data, colu) {
            //@Override
            public boolean isCellEditable(int x, int y) {
                if (y == 1) {
                    return true;
                } else {
                    return false;
                }
            }
        };

        tblGames.setModel(model);
        tblGames.getTableHeader().setPreferredSize(new Dimension(tblGames.getTableHeader().getPreferredSize().width, 35));
        JTableHeader head = tblGames.getTableHeader();
        head.setFont(head.getFont().deriveFont(Font.BOLD));

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        // tblGames.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);

        // model.setRowCount(20);
        TableColumn colou10 = tblGames.getColumnModel().getColumn(0);
        colou10.setMinWidth(80);
        colou10.setPreferredWidth(80);
        colou10.setMaxWidth(80);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chk2Player = new javax.swing.JRadioButton();
        chk3Player = new javax.swing.JRadioButton();
        chk4Player = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGames = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("Select the Game Type");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 290, -1));

        chk2Player.setBackground(null
        );
        buttonGroup1.add(chk2Player);
        chk2Player.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        chk2Player.setForeground(new java.awt.Color(0, 0, 204));
        chk2Player.setText("2 Player Game");
        chk2Player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk2PlayerActionPerformed(evt);
            }
        });
        jPanel1.add(chk2Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        chk3Player.setBackground(null
        );
        buttonGroup1.add(chk3Player);
        chk3Player.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        chk3Player.setForeground(new java.awt.Color(0, 0, 204));
        chk3Player.setText("3 Player Game");
        chk3Player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk3PlayerActionPerformed(evt);
            }
        });
        jPanel1.add(chk3Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        chk4Player.setBackground(null
        );
        buttonGroup1.add(chk4Player);
        chk4Player.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        chk4Player.setForeground(new java.awt.Color(0, 0, 204));
        chk4Player.setText("4 Player Game");
        chk4Player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk4PlayerActionPerformed(evt);
            }
        });
        jPanel1.add(chk4Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jButton3.setBackground(new java.awt.Color(56, 185, 33));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Quit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 455, 120, 30));

        tblGames.setBackground(new java.awt.Color(204, 128, 59));
        tblGames.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblGames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblGames);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 610, 230));

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Current Online Games");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 810, 40));

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 457, 120, 30));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk3PlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk3PlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk3PlayerActionPerformed

    private void chk4PlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk4PlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk4PlayerActionPerformed

    private void chk2PlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk2PlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk2PlayerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int typeid = 0;
        if (chk2Player.isSelected()) {
            typeid = 1;
        } else if (chk3Player.isSelected()) {
            typeid = 2;
        } else if (chk4Player.isSelected()) {
            typeid = 3;
        }
        
        game.connectWithGame(typeid);
        
        GameBoardScreen gameBoard= new GameBoardScreen();
        gameBoard.setVisible(true);
        this.dispose();
         
         ShowGrid();
         getGameData(); // show current Games
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chk2Player;
    private javax.swing.JRadioButton chk3Player;
    private javax.swing.JRadioButton chk4Player;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGames;
    // End of variables declaration//GEN-END:variables
}
